hellos3b/sjbha-bot

.gitignore, plugins/echos/Echos.js
Adds in !mocha, applies .idea directory to .gitignore for collaboration with IntelliJ IDEA developers
=> adds mocha command

config/plugins.config.js, plugins/covid19/index.js
Gives latest cases, deaths, recoveries as of latest date using covid19 command.
(First NodeJS script I've ever written).
=> Add covid19 command to pull latest numbers

plugins/covid19/index.js
=> add diffs to the command

plugins/covid19/index.js
Fixes capitalization errors, adds ability to add country to query
=> Add country search, fix capitalization

plugins/StockChart/index.js
1. Changed options from const to let to allow options variable to be reassigned.
2. Added condition to search for futures if `/` is detected within the symbol.
=> Added futures condition

.gitignore, config/plugins.config.js, package-lock.json, package.json, plugins/Minecraft/index.js, plugins/Minecraft/players.js
Currently added some things to gitignore like history/ and vscode/
Also added two commands, one for mc_info and mc_players.
mc_info gets server info and puts it in an embed
mc_players gets the player count for the server and posts it as a message
=> Commit for the Pull Request. Added mc_info and mc_players

plugins/Minecraft/index.js, plugins/echos/Echos.js
List player names as well as server details
=> new Minecraft command

plugins/echos/Echos.js
Using emojis that exist on the server, fixing commands that echo :missingemoji:
=> Repair Boba and Swirls echo commands

packages/backend/src/commands/fit/commands/help.ts
=> fit: remove scores from help menu

backend/src/commands/fit/admin/list.ts, backend/src/commands/fit/commands/profile.ts, backend/src/commands/fit/common/MemberList.ts, backend/src/commands/fit/features/post-workout.ts, backend/src/commands/fit/register.ts, backend/src/commands/fit/routes/activity-webhook.ts
=> fit: Fix fetching user nickname

backend/src/commands/meetup/commands/create.ts, backend/src/commands/meetup/commands/help.ts, backend/src/commands/meetup/features/render.ts, backend/src/commands/meetup/register.ts, backend/src/utils/string-formatting.ts
fixes #96 
!meetup - links to UI
!meetup help - shows help text
=> meetup: Added help command and link to create

backend/src/commands/meetup/commands/cancel.ts, backend/src/commands/meetup/commands/edit.ts
=> meetup: Check user IDs for edit and cancel meetup

backend/src/commands/meetup/commands/create.ts, backend/src/commands/meetup/commands/edit.ts, backend/src/commands/meetup/common/Meetup.ts, backend/src/commands/meetup/common/validateOptions.ts, backend/src/commands/meetup/db/meetups.ts, backend/src/commands/meetup/features/directory.ts, backend/src/commands/meetup/register.ts, backend/src/commands/meetup/routes/meetup.ts, frontend/src/pages/meetup/components/Category.svelte, frontend/src/pages/meetup/form/Details.svelte, frontend/src/pages/meetup/form/GenerateCommand.svelte, frontend/src/pages/meetup/store.ts
Categories (for now) just label the meetup with an emoji in directory
=> meetup: Add categories to meetups

backend/src/app/index.ts, backend/src/commands/fit/admin/promote.ts, backend/src/commands/meetup/admin/refresh.ts
Accidentally pushed the last merge without checking if I got everything right
=> Fixed missing reference bugs

backend/src/commands/meetup/features/directory.ts
closes #105 
When a meetup is added (instead of updated), the directory service will delete the directory messages and repost them, in order to turn the channel as "Unread"
=> New Meetups now notify directory channel

backend/src/commands/meetup/features/RenderAnnouncement.ts, backend/src/commands/meetup/features/directory.ts, backend/src/utils/string-formatting.ts
closes #114 
This simplifies the formatting because now it will auto update client side!
=> meetup: Switch time strings to discord markdown

backend/src/commands/meetup/features/RenderAnnouncement.ts
closes #116 
Fixed Google Calendar link to open up an actual Gcal invite
=> meetup: Add Google Calendar link creator

backend/src/commands/meetup/features/RenderAnnouncement.ts, frontend/src/pages/meetup/form/GenerateCommand.svelte
=> meetup: Add Copy to Clipboard

backend/src/commands/meetup/commands/create.ts
Closes #131 
Makes it easier to find from inside the thread
=> meetup: Pin announcement post in thread

backend/src/commands/fit/WorkoutEmbed.ts
Fixes #133 
Accidentally used the Run type twice in the activity embed generator
=> fit: Fix missing ride data

backend/.eslintrc, backend/package-lock.json, backend/package.json, backend/src/Main.ts, backend/src/__test__/MongoMemoryServer.ts, backend/src/app/DiscordClient.ts, backend/src/app/index.ts, backend/src/app/log.ts, backend/src/commands/fit/ActivityWebhook.ts, backend/src/commands/fit/Admin.ts, backend/src/commands/fit/Promotions.ts, backend/src/commands/fit/WorkoutEmbed.ts, backend/src/commands/meetup/commands/announce.ts, backend/src/commands/meetup/commands/cancel.ts, backend/src/commands/meetup/commands/create.ts, backend/src/commands/meetup/commands/edit.ts, backend/src/commands/meetup/db/meetups.ts, backend/src/commands/meetup/features/Directory.ts, backend/src/commands/meetup/features/EndMeetup.ts, backend/src/commands/meetup/features/KeepThreadsOpen.ts, backend/src/commands/meetup/features/UpdateRsvps.ts, backend/src/utils/Log.ts, backend/src/utils/MemberList.ts, package-lock.json, package.json
Created a new logger that pretty prints locally and adds a trace ID to each request so it's easier to find & debug
=> internal: Updating logging

web/pnpm-lock.yaml, web/src/pages/meetup/store.ts
=> fix(meetup): Populate links on edit

bot/src/commands/meetup/commands/edit.ts, bot/src/commands/meetup/features/UpdateRsvps.ts
=> fix(meetup): Timestamp not updating

bot/src/commands/meetup/RegisterMeetup.ts, bot/src/commands/meetup/features/RenderAnnouncement.ts, bot/src/commands/meetup/routes/gcal.ts
Fixes #135 
Details should show up on gcal now
=> fix(meetup): Add gcal url shortener

bot/src/commands/Tldr.ts
Just noticed you can use tldr outside of shitpost (forgot about that). updated it so it now shows private
=> feat(tldr): private viewing of list outside of shitpost

bot/src/commands/meetup/commands/announce.ts
=> meetup: fix announcement string spam

bot/package.json, bot/pnpm-lock.yaml, bot/src/app/DiscordClient.ts, bot/src/commands-rescript/Define.res, bot/src/commands/fit/Balance.ts, bot/src/commands/fit/Leaders.ts, bot/src/commands/fit/UserAuth.ts, bot/src/commands/fit/UserProfile.ts, bot/src/commands/fit/WorkoutEmbed.ts, bot/src/commands/meetup/commands/create.ts, bot/src/commands/meetup/commands/edit.ts, bot/src/commands/meetup/common/Meetup.ts, bot/src/commands/meetup/common/MeetupOptions.ts, bot/src/commands/meetup/features/Directory.spec.ts, bot/src/commands/meetup/features/Directory.ts, bot/src/commands/meetup/features/RenderAnnouncement.ts, bot/src/commands/meetup/features/UpdateRsvps.ts, bot/src/common/Discord.res, bot/src/common/Discord__Modal.res
Upticked the discord.js library, had to update a bunch of stuff.... relying on intellisense to hope i didn't miss anything
=> internal: Migrate to discord@14
